services:
  app:
    context: /opt/wsite/workout-wsite
    volumes:
      - sockets:/sockets
      - /opt/env/.env.prod:/app/.env.prod:ro      
    environment:
      - FLASK_ENV=prod
    env_file:
      - /opt/env/.env.prod      
    depends_on:
      - nginx 

  nginx:
    context: /opt/wsite/workout-wsite/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - sockets:/sockets
    restart: unless-stopped

volumes:
  sockets:
    driver: local
