version: '3.8'

services:
  app:
    build: ./app
      dockerfile: Dockerfile
    volumes:
      - sockets:/sockets
      - /opt/env/.env.prod:/app/.env.prod:ro      
    environment:
      - FLASK_ENV=prod
    env_file:
      - .env.prod      
    depends_on:
      - nginx 

  nginx:
    build: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - sockets:/sockets
    restart: unless-stopped

volumes:
  sockets:
    driver: local